[colors]
comparison_colors = [
	{r = 0x00, g = 0x3f, b = 0x5c},
	{r = 0xbc, g = 0x50, b = 0x90},
	{r = 0xff, g = 0xa6, b = 0x00},
	{r = 8, g = 34, b = 34},
	{r = 6, g = 139, b = 87},
	{r = 5, g = 215, b = 0},
	{r = 0, g = 0, b = 139},
	{r = 0, g = 20, b = 60},
	{r = 9, g = 0, b = 139},
	{r = 0, g = 255, b = 127},
]
