[colors]
comparison_colors = [
	{r=0xe6, g=0x00, b=0x49},
	{r=0x0b, g=0xb4, b=0xff},
	{r=0x50, g=0xe9, b=0x91},
	{r=0xe6, g=0xd8, b=0x00},
	{r=0x9b, g=0x19, b=0xf5},
	{r=0xff, g=0xa3, b=0x00},
	{r=0xdc, g=0x0a, b=0xb4},
	{r=0xb3, g=0xd4, b=0xff},
	{r=0x00, g=0xbf, b=0xa0},
]
